baseURL = "http://example.org/"
languageCode = "en-us"
title = "CAMS"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "Gerrit Kitts"
	description = "Combined Arms Mecha Wargame."
	copyright = "Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "red"
    	accent  = "teal"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	email   = "FIXME@email.com"


[[menu.main]]
	name   = "Quickstart"
	url    = "quickstart/"
	weight = 20

[[menu.main]]
	name   = "Rules"
	url    = "rules/"
	weight = 20

[[menu.main]]
	name   = "Forces of Battle"
	url    = "forces/"
	weight = 40

[[menu.main]]
	name   = "License"
	url    = "license/"
	weight = 70
