baseURL = "http://example.org/"
languageCode = "en-us"
title = "CAMS"
theme = "hugo-material-docs"

[params]
externalTitle = "DP9 Forum"

[[menu.shortcuts]]
name = "Javascript API"
url = "https://docs.surfly.com/javascript.html"
weight = 20
